version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: freelencly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend: # Indented under services
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/freelencly
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start"

volumes:
  pgdata:
